name: Cypress Cloud

on: 
  workflow_dispatch:
    inputs:
      cli:
        description: Run by cypress command line
        default: cypress/e2e/*

jobs:
  cypress-e2e-electron
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:22.12.0
      options: --user 1001
    steps:
      - name: Get code
        uses: actions/checkout@v4.2.2

      - name: Cypress run
        uses: cypress-io/github-action@v6.5.0
        with:
          install-command: yarn install
          browser: electron
          record: true
          group: UI Electron
          spec: ${{ github.event.inputs.spec }}
        env:
           CYPRESS_RECORD_KEY: 153bc88c-100f-47c2-b546-49c1ec86e30b
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  cypress-e2e-chrome
    needs: cypress-e2e-electron
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:22.12.0
      options: --user 1001
    steps:
      - name: Get code
        uses: actions/checkout@v4.2.2

      - name: Cypress run
        uses: cypress-io/github-action@v6.5.0
        with:
          install-command: yarn install
          browser: chrome
          record: true
          group: UI chrome
          spec: ${{ github.event.inputs.spec }}
        env:
           CYPRESS_RECORD_KEY: 153bc88c-100f-47c2-b546-49c1ec86e30b
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  cypress-e2e-firefox
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:22.12.0
      options: --user 1001
    steps:
      - name: Get code
        uses: actions/checkout@v4.2.2

      - name: Cypress run
        uses: cypress-io/github-action@v6.5.0
        with:
          install-command: yarn install
          browser: firefox
          record: true
          group: UI firefox
          spec: ${{ github.event.inputs.spec }}
        env:
           CYPRESS_RECORD_KEY: 153bc88c-100f-47c2-b546-49c1ec86e30b
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        

   

   
